# Generated by Django 3.0.3 on 2020-02-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_pages_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='photo',
            field=models.ImageField(default='name1.png', upload_to='gallery'),
        ),
    ]
