# Generated by Django 3.0.3 on 2020-03-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=100)),
                ('Lastname', models.CharField(max_length=100)),
                ('Email', models.TextField()),
                ('Password', models.TextField()),
                ('Confirm', models.TextField()),
                ('Code', models.IntegerField()),
                ('PhoneNo', models.IntegerField()),
                ('Address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=100)),
                ('Lastname', models.CharField(max_length=100)),
                ('Email', models.TextField()),
                ('Password', models.TextField()),
                ('Confirm', models.TextField()),
                ('Aadhar', models.TextField()),
                ('Code', models.IntegerField()),
                ('PhoneNo', models.IntegerField()),
                ('Address', models.TextField()),
            ],
        ),
    ]
