# Generated by Django 3.0.3 on 2020-03-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinfo',
            name='Username',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vinfo',
            name='Username',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
