# Generated by Django 3.0.3 on 2020-03-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200320_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinfo',
            name='Firstname',
        ),
        migrations.RemoveField(
            model_name='cinfo',
            name='Lastname',
        ),
        migrations.AddField(
            model_name='cinfo',
            name='Fullname',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
