# Generated by Django 3.0.3 on 2020-03-22 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200321_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinfo',
            name='Confirm',
        ),
    ]
